// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"backend/internal/models"
	"github.com/sev-2/raiden/pkg/resource"
)

func RegisterModels() {
	resource.RegisterModels(
		&models.AuditLogEntries{},
		&models.BookingController{},
		&models.Doctor{},
		&models.Faskes{},
		&models.FlowState{},
		&models.Identities{},
		&models.Instances{},
		&models.JadwalDoctors{},
		&models.MfaAmrClaims{},
		&models.MfaChallenges{},
		&models.MfaFactors{},
		&models.OneTimeTokens{},
		&models.Poli{},
		&models.RefreshTokens{},
		&models.Reservation{},
		&models.RolePermissions{},
		&models.SamlProviders{},
		&models.SamlRelayStates{},
		&models.SchemaMigrations{},
		&models.Sessions{},
		&models.SsoDomains{},
		&models.SsoProviders{},
		&models.UserRoles{},
		&models.Users{},
	)
}
