// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"backend/internal/controllers"
	"backend/internal/models"
	"github.com/sev-2/raiden"
	raiden_controllers "github.com/sev-2/raiden/pkg/controllers"
	"github.com/valyala/fasthttp"
)

func RegisterRoute(server *raiden.Server) {
	server.RegisterRoute([]*raiden.Route{
		raiden.NewRouteFromController(&raiden_controllers.StateReadyController{}, []string{fasthttp.MethodPost}),
		{
			Type:       raiden.RouteTypeRest,
			Path:       "/doctor",
			Methods:    []string{},
			Controller: &controllers.BooksController{},
			Model:      models.Doctor{},
		},
		{
			Type:       raiden.RouteTypeCustom,
			Path:       "/hello",
			Methods:    []string{fasthttp.MethodGet},
			Controller: &controllers.HelloWorldController{},
		},
		{
			Type:       raiden.RouteTypeRest,
			Path:       "/jadwal_doctors",
			Methods:    []string{},
			Controller: &controllers.JadwalDoctorsController{},
			Model:      models.JadwalDoctors{},
		},
	})
}
