// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"backend/internal/rpc"
	"github.com/sev-2/raiden/pkg/resource"
)

func RegisterRpc() {
	resource.RegisterRpc(
		&rpc.CustomAccessTokenHook{},
	)
}
