PROJECT_NAME: backend
PROJECT_ID: olupukupsuudviumjakq
DEPLOYMENT_TARGET: cloud

MODE: bff
ACCESS_TOKEN: sbp_252cd479991a418042c95b8d275bffd9ffc8bd67
ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sdXB1a3Vwc3V1ZHZpdW1qYWtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNzg2NDYsImV4cCI6MjA1NDk1NDY0Nn0.cia2tjIo4qF8-i9z-3f97t2a-ZDReff5JaOJBLQifiY
SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sdXB1a3Vwc3V1ZHZpdW1qYWtxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczOTM3ODY0NiwiZXhwIjoyMDU0OTU0NjQ2fQ.AdNHFAQhkHhD1sN76u5Eym5jQ00imB8ij-_-iBNdGcs

SUPABASE_API_URL: https://api.supabase.com
SUPABASE_API_BASE_PATH: 
SUPABASE_PUBLIC_URL: https://olupukupsuudviumjakq.supabase.co
SERVER_HOST: 127.0.0.1
SERVER_PORT: 8002
SERVER_DNS: 

ENVIRONMENT: development
VERSION: 1.0.0

ALLOWED_TABLES: '*'
SCHEDULE_STATUS: 'off'

BREAKER_ENABLE: true

TRACE_ENABLE: false
TRACE_COLLECTOR: 
TRACE_COLLECTOR_ENDPOINT: 

MAX_SERVER_REQUEST_BODY_SIZE: 8388608

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
